title: Jinyuan Yang's Homepage
page-top-title: Jinyuan Yang
top-section-bg-text: Applied Psychology
home-subtitle: Jinyuan Yang&ensp;|&ensp;杨觐元
copyright-text: '&copy; Jinyuan Yang 2023-2025. All Rights Reserved.'
